### ISSUE TITLE
Нарисовать рабочий макет интерфейса главного окна

### ISSUE THREAD

**Issue by YKamenev322** [hidronautics/PoolsideGUI#12]
Я предлагаю сделать сначала главное окно. То есть то окно, которое видит оператор при управлении подводным аппаратом. Его описание можно найти по [ссылке](https://yadi.sk/d/L9_QJg545RbVLg) (тз на пульт), уже рисовавшиеся макеты можно найти там же. Настоятельно рекомендую обсудить получившееся макеты (или макет) с командой (будет прекрасно это сделать на общем собрании).

**Comment by vladushked** [comment]
Думаю стоит сделать 2 варианта главного окна
1 - Вариант когда у нас аналоговая камера. На главном окне только курс, дифферент, крен, глубина; отображение состояния винтомоторов (в идеале показывать нагрузку, но можно просто работает/не работает) и остальных устройств.
2 - Вариант когда у нас есть цифровая камера. Тогда большую часть окна занимает изображение с передней камеры, а все остальное разнесено по бокам. 
3 - Еще вариант когда несколько цифровых камер. В этом случае можно все показания датчиков сделать мелкими и пихнуть дополнительные изображения с других камер.

**Comment by YKamenev322** [comment]
> Думаю стоит сделать 2 варианта главного окна
> 1 - Вариант когда у нас аналоговая камера. На главном окне только курс, дифферент, крен, глубина; отображение состояния винтомоторов (в идеале показывать нагрузку, но можно просто работает/не работает) и остальных устройств.
> 2 - Вариант когда у нас есть цифровая камера. Тогда большую часть окна занимает изображение с передней камеры, а все остальное разнесено по бокам.
> 3 - Еще вариант когда несколько цифровых камер. В этом случае можно все показания датчиков сделать мелкими и пихнуть дополнительные изображения с других камер.

Если у нас цифровая камера, то она на другом экране. Нечего ей тут делать, ничего не будет видно.
